### ISSUE TITLE
Devation Errors in Test Verification

### ISSUE THREAD

**Issue by ddevereaux** [NOAA-PMEL/EDD-OSCompass_Test#1]
I'm encountering deviation errors that are way outside of what would be expected when entering a desired degree. This occurs in the "testing accuracy of calibration" portion of the code when the user enters a heading. I think this may be due to how "direction" is defined in both compass.py and in calibration.py.  Sometimes it responds with a normal deviation of <1.0 while others it is around 90.0 or 180.0

**Comment by AlexMTurpin** [comment]
I wonder if it's a timing issue when doing the soft iron calibration. If
one of the compasses is lagging a step or two behind the others during the
soft iron calibration it would report a multiple of 90 degrees of deviation.

**Comment by MCasari-PMEL** [comment]
Has this been resolved?

**Comment by AlexMTurpin** [comment]
Yes. 
The incoming serial needed to be flushed before reading a new line. I think this has to do with the Serial.read_until() function not properly working.
