### ISSUE TITLE
Error in CSV Export

### ISSUE THREAD

**Issue by ddevereaux** [NOAA-PMEL/EDD-OSCompass_Test#2]
I received the attached error when completing the roll verification step.  The compasses had no errors prior to this step. 
![compass_error2](https://user-images.githubusercontent.com/33729388/36233015-e2c9d74c-1198-11e8-98fd-ca61dff50358.PNG)

**Comment by AlexMTurpin** [comment]
The previous version of Compass.py only required the following headings:
**Serial Number
Deviation
PMEL Owner
Test Date
Compass Current
Test Result**

The most recent update from 2/5/2018 requires that the following headings be appended to the existing ones from above:
**Average Heading Deviation
Average Pitch Deviation
Average Roll Deviation**

If this problem occurs again a simple modification to the first line of "OS4000T.csv" to include the 3 average deviation lines will fix the problem.
